# Generated by Django 2.2.4 on 2020-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShows', '0002_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
